In [29]:
import pandas as pd

tabela = pd.read_csv('exportacoes_franca.csv')
display(tabela)
display(tabela.info())

#Analise da Exportacoes da França ao longo dos anos
tabela_anos_exportacoes = tabela[["Year", "US$ FOB"]].groupby('Year').sum().reset_index()
def formatar_valor(valor):
    return f"US$ {valor:,.2f}"
tabela_anos_exportacoes["US$ FOB"] = tabela_anos_exportacoes["US$ FOB"].apply(formatar_valor)
display(tabela_anos_exportacoes)

#Produtos mais exportados pela França
tabela_produtos_exportados = tabela[["SH2 Description", "US$ FOB"]].groupby('SH2 Description').sum().reset_index().sort_values(by='US$ FOB', ascending=False)
tabela_produtos_exportados["US$ FOB"] = tabela_produtos_exportados["US$ FOB"].apply(formatar_valor)
display(tabela_produtos_exportados)

#Cidade que mais exportou em 2020
tabela_cidade_2020 = tabela[tabela["Year"] == 2020][["City", "US$ FOB"]].groupby('City').sum().reset_index().sort_values(by='US$ FOB', ascending=False)
tabela_cidade_2020["US$ FOB"] = tabela_cidade_2020["US$ FOB"].apply(formatar_valor)
display(tabela_cidade_2020)

#Quais produtos mais exportados cidades de 2020
cidade1 = tabela_cidade_2020.iloc[0]['City']
cidade2 = tabela_cidade_2020.iloc[1]['City']
tabela_cidade_2020 = tabela[(tabela["Year"] == 2020) & (tabela["City"].isin([cidade1, cidade2]))][["SH2 Description", "US$ FOB"]].groupby('SH2 Description').sum().reset_index().sort_values(by='US$ FOB', ascending=False)
tabela_cidade_2020["US$ FOB"] = tabela_cidade_2020["US$ FOB"].apply(formatar_valor)
display(tabela_cidade_2020)
print(f"Produtos mais exportados pela cidade {cidade1} em 2020 foi {tabela_cidade_2020.iloc[0]['SH2 Description']} com valor de {tabela_cidade_2020.iloc[0]['US$ FOB']}")

,Year,Month,Country,City,SH4 Code,SH4 Description,SH2 Code,SH2 Description,Economic Block,US$ FOB,Net Weight
0,2016,1,France,Águas Mornas - SC,303,"Fish, frozen, excluding fish fillets and other...",3,"Fish and crustaceans, molluscs and other aquat...",Europe,79360,14150
1,2016,1,France,Águas Mornas - SC,303,"Fish, frozen, excluding fish fillets and other...",3,"Fish and crustaceans, molluscs and other aquat...",European Union (EU),79360,14150
2,2016,1,France,Águas Mornas - SC,304,Fish fillets and other fish meat (whether or n...,3,"Fish and crustaceans, molluscs and other aquat...",Europe,69412,9385
3,2016,1,France,Águas Mornas - SC,304,Fish fillets and other fish meat (whether or n...,3,"Fish and crustaceans, molluscs and other aquat...",European Union (EU),69412,9385
4,2016,1,France,Alfenas - MG,901,"Coffee, whether or not roasted or decaffeinate...",9,"Coffee, tea, maté and spices",Europe,180914,57600
...,...,...,...,...,...,...,...,...,...,...,...
142355,2020,12,France,Vinhedo - SP,8424,Mechanical appliances (whether or not hand-ope...,84,"Nuclear reactors, boilers, machinery and mecha...",European Union (EU),2316,4
142356,2020,12,France,Vitória de Santo Antão - PE,714,"Manioc, arrowroot, salep, Jerusalem artichokes...",7,Edible vegetables and certain roots and tubers,Europe,27060,26400
142357,2020,12,France,Vitória de Santo Antão - PE,714,"Manioc, arrowroot, salep, Jerusalem artichokes...",7,Edible vegetables and certain roots and tubers,European Union (EU),27060,26400
142358,2020,12,France,Xapuri - AC,4409,Wood (including strips and friezes for parquet...,44,Wood and articles of wood; wood charcoal,Europe,31111,23045
142359,2020,12,France,Xapuri - AC,4409,Wood (including strips and friezes for parquet...,44,Wood and articles of wood; wood charcoal,European Union (EU),31111,23045

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142360 entries, 0 to 142359
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Year             142360 non-null  int64
 1   Month            142360 non-null  int64
 2   Country          142360 non-null  object
 3   City             142360 non-null  object
 4   SH4 Code         142360 non-null  int64
 5   SH4 Description  142360 non-null  object
 6   SH2 Code         142360 non-null  int64
 7   SH2 Description  142360 non-null  object
 8   Economic Block   142360 non-null  object
 9   US$ FOB          142360 non-null  int64
 10  Net Weight       142360 non-null  int64
dtypes: int64(6), object(5)
memory usage: 11.9+ MB

None

   Year               US$ FOB
0  2016  US$ 4,615,500,082.00
1  2017  US$ 4,448,705,456.00
2  2018  US$ 5,239,424,416.00
3  2019  US$ 5,218,723,612.00
4  2020  US$ 3,967,594,810.00

                                      SH2 Description               US$ FOB
75  Residues and waste from the food industries; o...  US$ 5,641,498,484.00
57                                 Ores, slag and ash  US$ 3,404,353,274.00
54  Nuclear reactors, boilers, machinery and mecha...  US$ 1,889,781,694.00
72  Pulp of wood or of other fibrous cellulosic ma...  US$ 1,855,424,642.00
0             Aircraft, spacecraft, and parts thereof  US$ 1,253,007,710.00
..                                                ...                   ...
89  Umbrellas, sun umbrellas, walking-sticks, seat...         US$ 18,872.00
19                          Cork and articles of cork         US$ 10,974.00
94  Wool, fine or coarse animal hair; horsehair ya...          US$ 2,540.00
85                           Tin and articles thereof          US$ 2,460.00
64              Photographic or cinematographic goods            US$ 148.00

[97 rows x 2 columns]

                            City             US$ FOB
180         Duque de Caxias - RJ  US$ 279,405,596.00
326  Luís Eduardo Magalhães - BA  US$ 265,328,132.00
456            Ponta Grossa - PR  US$ 187,777,016.00
576     São José dos Campos - SP  US$ 172,939,276.00
508          Rio de Janeiro - RJ  US$ 122,522,214.00
..                           ...                 ...
393            Não-Me-Toque - RS           US$ 42.00
164                 Cubatão - SP           US$ 40.00
226                Holambra - SP           US$ 10.00
587    São Sebastião do Caí - RS            US$ 6.00
489           Quatro Pontes - PR            US$ 0.00

[648 rows x 2 columns]

                                      SH2 Description             US$ FOB
17  Residues and waste from the food industries; o...  US$ 269,314,082.00
11  Nuclear reactors, boilers, machinery and mecha...  US$ 185,816,982.00
8   Mineral fuels, mineral oils, bituminous substa...   US$ 67,355,688.00
1                           Articles of iron or steel    US$ 9,118,714.00
12  Optical, photographic, cinematographic instrum...    US$ 3,013,092.00
10                        Nickel and articles thereof    US$ 2,951,286.00
5   Electrical machinery and equipment and parts t...    US$ 2,595,048.00
7                           Lead and articles thereof    US$ 1,660,180.00
18                        Rubber and articles thereof    US$ 1,379,296.00
13                                  Organic chemicals      US$ 535,136.00
20  Vehicles other than railway or tramway rolling...      US$ 353,958.00
15                      Plastics and articles thereof      US$ 228,638.00
0                      Aluminium and articles thereof      US$ 168,522.00
3                         Copper and articles thereof      US$ 138,466.00
19  Tools, implements, cutlery, spoons and forks, ...       US$ 33,864.00
4   Edible fruit and nuts; peel of citrus fruits o...       US$ 28,324.00
2   Articles of stone, plaster, cement, asbestos, ...       US$ 16,856.00
9                     Miscellaneous chemical products       US$ 11,984.00
6                                 Glass and glassware        US$ 8,430.00
16  Railway or tramway locomotives, rolling-stock ...        US$ 3,666.00
14  Paper and paperboard; articles of paper pulp, ...        US$ 1,516.00

Produtos mais exportados pela cidade Duque de Caxias - RJ em 2020 foi Residues and waste from the food industries; others com valor de US$ 269,314,082.00